# Generated by Django 5.1.3 on 2025-07-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_marca_alter_car_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
